/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Post } from "./global/models/post.model";
import { TrendingPost } from "./global/models/trending-post";
export namespace Components {
    interface FrontPage {
    }
    interface MyComponent {
        "first"?: string;
        "last"?: string;
    }
    interface NavBar {
    }
    interface PostCard {
        "mode": 'card' | 'compact' | 'classic';
        /**
          * The post data for the post card
         */
        "post": Post;
    }
    interface PostFilter {
    }
    interface ToolTip {
        "base": HTMLElement;
        "horizontalPos": 'left' | 'center' | 'right';
        "verticalPos": 'top' | 'bottom' | 'auto';
    }
    interface TrendingCard {
        "post": TrendingPost;
    }
}
declare global {
    interface HTMLFrontPageElement extends Components.FrontPage, HTMLStencilElement {
    }
    var HTMLFrontPageElement: {
        prototype: HTMLFrontPageElement;
        new (): HTMLFrontPageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLPostCardElement extends Components.PostCard, HTMLStencilElement {
    }
    var HTMLPostCardElement: {
        prototype: HTMLPostCardElement;
        new (): HTMLPostCardElement;
    };
    interface HTMLPostFilterElement extends Components.PostFilter, HTMLStencilElement {
    }
    var HTMLPostFilterElement: {
        prototype: HTMLPostFilterElement;
        new (): HTMLPostFilterElement;
    };
    interface HTMLToolTipElement extends Components.ToolTip, HTMLStencilElement {
    }
    var HTMLToolTipElement: {
        prototype: HTMLToolTipElement;
        new (): HTMLToolTipElement;
    };
    interface HTMLTrendingCardElement extends Components.TrendingCard, HTMLStencilElement {
    }
    var HTMLTrendingCardElement: {
        prototype: HTMLTrendingCardElement;
        new (): HTMLTrendingCardElement;
    };
    interface HTMLElementTagNameMap {
        "front-page": HTMLFrontPageElement;
        "my-component": HTMLMyComponentElement;
        "nav-bar": HTMLNavBarElement;
        "post-card": HTMLPostCardElement;
        "post-filter": HTMLPostFilterElement;
        "tool-tip": HTMLToolTipElement;
        "trending-card": HTMLTrendingCardElement;
    }
}
declare namespace LocalJSX {
    interface FrontPage {
    }
    interface MyComponent {
        "first"?: string;
        "last"?: string;
    }
    interface NavBar {
        "onSearch"?: (event: CustomEvent<string>) => void;
    }
    interface PostCard {
        "mode"?: 'card' | 'compact' | 'classic';
        /**
          * The post data for the post card
         */
        "post"?: Post;
    }
    interface PostFilter {
        "onNewMode"?: (event: CustomEvent<'card' | 'classic' | 'compact'>) => void;
    }
    interface ToolTip {
        "base"?: HTMLElement;
        "horizontalPos"?: 'left' | 'center' | 'right';
        "verticalPos"?: 'top' | 'bottom' | 'auto';
    }
    interface TrendingCard {
        "post"?: TrendingPost;
    }
    interface IntrinsicElements {
        "front-page": FrontPage;
        "my-component": MyComponent;
        "nav-bar": NavBar;
        "post-card": PostCard;
        "post-filter": PostFilter;
        "tool-tip": ToolTip;
        "trending-card": TrendingCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "front-page": LocalJSX.FrontPage & JSXBase.HTMLAttributes<HTMLFrontPageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "post-card": LocalJSX.PostCard & JSXBase.HTMLAttributes<HTMLPostCardElement>;
            "post-filter": LocalJSX.PostFilter & JSXBase.HTMLAttributes<HTMLPostFilterElement>;
            "tool-tip": LocalJSX.ToolTip & JSXBase.HTMLAttributes<HTMLToolTipElement>;
            "trending-card": LocalJSX.TrendingCard & JSXBase.HTMLAttributes<HTMLTrendingCardElement>;
        }
    }
}
